---
allow-admin-nomutate: false
allow-admin-nomutate-toggle: 7b068a99-c02b-410a-bd59-3514bac85e7a
dockerhub-registry: registry.hub.docker.com
mutate-ignored-images:
- goharbor/chartmuseum-photon
- goharbor/harbor-core
- goharbor/harbor-db
- goharbor/harbor-jobservice
- goharbor/notary-server-photon
- goharbor/notary-signer-photon
- goharbor/harbor-portal
- goharbor/redis-photon
- goharbor/registry-photon
- goharbor/trivy-adapter-photon
