---
allow-admin-nomutate: false
allow-admin-nomutate-toggle: 2d77b689-dc14-40a5-8971-34c62999335c
dockerhub-registry: registry.hub.docker.com
mutate-ignored-images:
- goharbor/chartmuseum-photon
- goharbor/harbor-core
- goharbor/harbor-db
- goharbor/harbor-jobservice
- goharbor/notary-server-photon
- goharbor/notary-signer-photon
- goharbor/harbor-portal
- goharbor/redis-photon
- goharbor/registry-photon
- goharbor/trivy-adapter-photon