apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-config
data:
  config.yaml: |-
    mutate-ignored-images:
    - goharbor/chartmuseum-photon
    - goharbor/harbor-core
    - goharbor/harbor-db
    - goharbor/harbor-jobservice
    - goharbor/notary-server-photon
    - goharbor/notary-signer-photon
    - goharbor/harbor-portal
    - goharbor/redis-photon
    - goharbor/registry-photon
    - goharbor/trivy-adapter-photon
    kubernetes:
      namespace: ingress-nginx
      service-name: webhook
    certificate-authority:
      certificate: |
        -----BEGIN CERTIFICATE-----
        -----END CERTIFICATE-----
      private-key: |
        -----BEGIN RSA PRIVATE KEY-----
        -----END RSA PRIVATE KEY-----    
