---
apiVersion: v1
kind: Service
metadata:
  name: webhook
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  selector:
    app: mutating-webhook
  type: ClusterIP
