---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-mutation
webhooks:
  - name: pod-mutation.default.svc
    clientConfig:
      service:
        name: webhook
        namespace: default
        path: "/api/v1/mutate/pod"
    rules:
      - operations: ["CREATE", ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore