# Custom Labels Webhook Configuration - Production Environment

# Admission control settings
allow-admin-nomutate: false
dry-run: false
enable-labeling: true
label-all-workloads: true

# Excluded namespaces (in addition to system namespaces)
excluded-namespaces:
  - "kube-system"
  - "kube-public"
  - "kube-node-lease"

# Custom labels to apply to all workloads
custom-labels:
  company: "your-company"
  environment: "production"
  cost-center: "engineering"
  data-classification: "internal"
  compliance: "required"
  backup: "enabled"
  monitoring: "full"
  security-scan: "required"
  data-retention: "7years"

# Kubernetes configuration
kubernetes:
  namespace: "webhook-system"
  service-name: "prod-custom-labels-webhook"
