apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: custom-labels-webhook-production

namespace: webhook-system

resources:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production
  tier: production

images:
  - name: webhook-image
    newName: quay.io/your-org/custom-labels-webhook
    newTag: v1.0.0

replicas:
  - name: custom-labels-webhook
    count: 3

configMapGenerator:
  - name: webhook-config
    behavior: merge
    literals:
      - organization=your-company
      - environment=production
      - cluster-name=production-cluster
    files:
      - config.yaml

patchesStrategicMerge:
  - deployment-patch.yaml

patches:
  - target:
      kind: Deployment
      name: custom-labels-webhook
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DRY_RUN
          value: "false"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_LEVEL
          value: "40"
