---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-labels-webhook
  namespace: kube-system
  labels:
    app: custom-labels-webhook
    component: mutating-webhook
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-labels-webhook
  labels:
    app: custom-labels-webhook
    component: mutating-webhook
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-labels-webhook
  labels:
    app: custom-labels-webhook
    component: mutating-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-labels-webhook
subjects:
- kind: ServiceAccount
  name: custom-labels-webhook
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: custom-labels-webhook
  namespace: kube-system
  labels:
    app: custom-labels-webhook
    component: mutating-webhook
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-labels-webhook
  namespace: kube-system
  labels:
    app: custom-labels-webhook
    component: mutating-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: custom-labels-webhook
subjects:
- kind: ServiceAccount
  name: custom-labels-webhook
  namespace: kube-system
